### PR TITLE
Switch to python-native authentification via azure-identity

### PR DESCRIPTION
**Pull request by temporaer**
This PR removes the dotnet dependency in favor or a python-native solution based on azure-identity.

The dotnet dependency is a binary operating system package which cannot be installed with pip, and often complicates installation of python packages from devops feeds.

Joint work with @javuc1.

### CODE REVIEW

**Comment by FSund** [comment]
Any progress on this? The dotnet (SDK!) is causing some issues for us.

**Comment by jslorrma** [comment]
Is this PR still considered and will it be merged at some point?

We are using ADO Artifacts in our organization and we are struggling a lot with consistently setting up artifacts-keyring over different environments (Win 10/11, Unix, OSX, WSL, ...), because of it's dotnet dependency in UNIX senvironments. So a python-native solution, that at least as fallback, could work without artifacts-credprovider would be highly beneficial. 

Currently we are patching installations in WSL environments for instance, to call the `CredentialProvider.Microsoft.exe` instead of the `CredentialProvider.Microsoft.dll` with `dotnet exec`, to make it work. The `dotnet exec ...` [here](microsoft/artifacts-credprovider/blob/master/src/artifacts-credprovider-conda/src/activate/artifacts-cred.py#L61) is not working and just fails, without any error.

**Comment by temporaer** [comment]
I'm not sure whether the owning team monitors this, but if they do, please consider that it's a currently a *huge* pain to use artifacts keyring outside the seemingly narrow use cases they seem to be targeting. Given that this is Microsoft's only way to securely distribute private python packages, I wish  the team would listen and adopt a Linux/python friendly solution using the standard SDK rather than messing with huge binary dependencies that need manual installation and break on every other system.

**Comment by jslorrma** [comment]
> > the package can be found here: keyrings.artifacts (LINK REMOVED)
> 
> Please don't put packages on Test PyPI and then invite others to install them. That's not at all secure - it's worse than insecure. Test PyPI is literally only for making sure your upload command works. NEVER install anything from there.
>

Thanks for your advice. I never meant to put the test.pypi link, but the pyypi one. Anyhow, I'll remove it and just leave the one to the GitHub repo

**Comment by embetten** [comment]
We are working on supporting python MSAL without the dotnet runtime by shipping a self-contained version of the artifacts-credprovider as we do not want to be maintaining multiple implementations of the MSAL wrapper. 

We appreciate your patience until that work is completed. Closing this PR.

**Pull request closed without merging**
